### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [vitaut/vitaut.github.io#1]
The website being hosted at zverovich.net is inaccessible over IPv6.

This can be fixed by using a CNAME record, as described [here](https://help.github.com/articles/setting-up-a-custom-subdomain), instead of an apex domain.

**Comment by vitaut** [comment]
There is already a `CNAME` record for `www.zverovich.net` and http://www.zverovich.net should be accessible via ipv6 (according to http://ipv6-test.com/validate.php). Are you suggesting replacing the `A` record with a `CNAME` record for `zverovich.net`?

**Comment by tambry** [comment]
@vitaut www.zverovich.net is indeed accessible over IPv6, but it simply redirects to zverovich.net, which is not accessible over IPv6.

My suggestions is to replace the `A` record on zverovich.net with a `CNAME` record for `vitaut.github.io`, as described in [this GitHub help article](https://help.github.com/articles/setting-up-a-custom-subdomain) – this should make zverovich.net accessible over IPv6.

**Comment by vitaut** [comment]
Unfortunately `CNAME` cannot be applied to a root domain, like `zverovich.net`, only to a subdomain.

**Comment by tambry** [comment]
Ah, sorry, didn't realize that.
Maybe you could redirect people to www.zerovich.net and add the CNAME to that?

**Comment by vitaut** [comment]
I changed https://github.com/vitaut/vitaut.github.io/blob/master/CNAME to point to www.zverovich.net, so it should no longer be redirected to zverovich.net. Thanks!

**Comment by tambry** [comment]
That indeed works now. Thanks!
