### ISSUE TITLE
rss/atom feed missing

### ISSUE THREAD

**Issue by a4z** [vitaut/vitaut.github.io#5]
https://www.zverovich.net/ redirects me now to https://vitaut.net

The previous page, zverovich.ne,  had an atom feed.
I can not find any rss/atom feed at vitaut.net. 

Maybe it got lost when porting the side?
Can you re-add one?

**Comment by vitaut** [comment]
The site moved to a new domain and the feed is now here: https://vitaut.net/index.xml.

**Comment by a4z** [comment]
Thanks! Nice to have you back on the [SwedenCpp C++ blog feed](https://www.swedencpp.se/blogs)
